### ISSUE TITLE
Validate/Diff/Verify integrity of packages

### ISSUE THREAD

**Issue by chadbramwell** [GlitchEnzo/NuGetForUnity#126]
It'd be nice to have a button to 'verify' the integrity of an installed package.

The main reason for this request stems from an optimization we are trying - adding everything under /Assets/Packages to .gitignore. By doing this, we make it faster to download projects using the same packages (due to the cache) and we reduce the total size of our gitrepos (because we don't check our projects in, just the packages.config file).

When modifications need to happen inside of packages there's a bunch of options we could go down (like copy & paste, adding exception to gitignore, PR against the package's repo, etc...). But I'm more concerned about the situation where new code is written against a modified package, that code gets committed, and either you get a build failure (because you have a build server setup!) or other users discover a broken build.

So my thought is, if we had a simple tool to verify the integrity of the packages (perhaps Nuget already does? I'm not a power-user.) within the Unity UI, then we could take steps to verify our code is in a prime state.

**Comment by GlitchEnzo** [comment]
I'm a bit confused by this request, so I need some further clarification.

> an optimization we are trying - adding everything under /Assets/Packages to .gitignore.

This should be the standard way of using NuGetForUnity.  It's suggested in the readme:
 > Note: You'll probably want your Packages folder to be ignored by your version control software to prevent NuGet packages from being versioned in your repository.
---
> When modifications need to happen inside of packages

Are you saying that you are modifying the contents of a package inside the Packages folder after installing them into your project? If that's the case, I'd recommend using a junction/symlink to pull in the source code directly instead of modifying the installed package contents.  I do have an [outstanding issue](https://github.com/GlitchEnzo/NuGetForUnity/issues/39) to implement something like the NuGet Reference Switcher, which would help with this workflow. #39 

> new code is written against a modified package, that code gets committed, and either you get a build failure

If a package is getting modified and a project depends on those changes, then a newer version of the package should be released (even if it's only a "prerelease" version).

> if we had a simple tool to verify the integrity of the packages

I'm not exactly sure what you're wanting this to do.  Are you wanting it to compare the package installed versus the package in the cache or on the server?

**Comment by chadbramwell** [comment]
> Are you wanting it to compare the package installed versus the package in the cache or on the server?

Yes!

The pace of our projects doesn't allow us to change a library, wait for the code review, etc... To get a new version of some nuget package so that we can continue working. I'm assuming this is the case for a vast majority of projects out there but if there's some other solution I'd love to hear about it.

So we need to make a change to a library. We would make the change, add modified library to source control and continue on to not block the team. Once we find the time, we could push our changes to a library holder and get them in.

That's where this request comes in, it would make it easier to diff any changes to upload when the time comes. It also has the added benefit of verifying no accidental modifications to a library occurred before submitting code.

**Comment by chadbramwell** [comment]
> Are you saying that you are modifying the contents of a package inside the Packages folder after installing them into your project?

Yes! It can happen.

> then a newer version of the package should be released (even if it's only a "prerelease" version).

Is it possible to do this when you don't have access to a libraries repo? Is this a generally accepted practice by a majority of library writers who use NuGet?

**Comment by jwittner** [comment]
@chadbramwell packages we download I believe do contain the nuspec file that was used to create them. We could create modified pre-releases to our internal NuGet feeds with modified versions of public packages. Assuming of course, that's in line with the License of the package.
