### ISSUE TITLE
Support for installing NugetForUnity via UPM

### ISSUE THREAD

**Issue by popcron** [GlitchEnzo/NuGetForUnity#223]
Unity recently implemented support for the package manager to be able to reference github repos as packages using the following format:
`"com.popcron.console": "https://github.com/popcron/console.git"`

With support for commitish identifiers, so you are able to target a specific branch if you add `#branch`.
They don't have any support for targeting a specific directory within a repository, so organizing it by folder isn't possible. Though they are planning on supporting it later on according to their forum replies [here](https://forum.unity.com/threads/git-support-on-package-manager.573673/).

The format for making a repository recognizable as a package by UPM, is to have a package.json file inside, and any .meta files included and up to date ([documentation](https://docs.unity3d.com/Packages/com.unity.package-manager-ui@1.8/manual/index.html#advanced-package-topics)). My workflow with this, is to work with the repository cloned to my desktop, and reference it locally so that I am able to generate valid .meta files.
`"com.popcron.console": "file:/Users/phill/source/repos/Popcron.Console"`

Cheers!

**Comment by Thaina** [comment]
+1

**Comment by jwittner** [comment]
Not sure what the ask is for here from NuGetForUnity, i.e. how should the project support UPM? Closing for now, but if there's a good idea for how this project can leverage or support UPM we can reopen.

**Comment by Thaina** [comment]
@jwittner There is a way you could put some json file in format of UPM into the root of this repo and UPM could import the repo as package

**Comment by Thaina** [comment]
Any progress?

**Comment by jwittner** [comment]
@Thaina - not that I know of, but we're always open to PRs if you want to add support for shaping a package out of the repo for distribution on UPM. I do have access to a public feed that I can distribute from once we have a package, but don't have bandwidth to do the packaging.

**Comment by as3mbus** [comment]
would love to see this happen. 
it would helps a lot with package that require dll fetched from nuget and less dependency handling through UPM.

i would like to implement this. 
but i haven't even tried the plugin. i'd try it later 

just for an up vote i included a blog that can help anyone interested with UPM.

https://gametorrahod.com/how-to-asmdef-upm/

**Comment by shiena** [comment]
You can use path query parameter from unity2019.3.4f1 and unity2020.1a21.
https://forum.unity.com/threads/some-feedback-on-package-manager-git-support.743345/#post-5425311

**Comment by andybak** [comment]
I'd just like to add my vote to this. The primary motivation for using packages is to keep my repo/project clean of 3rd party code.

It seems like a step backwards that the only way to make use of NuGet packages is to add a big glob of 3rd party code to my project.

**Comment by popcron** [comment]
Agreed

**Comment by popcron** [comment]
> @Thaina - not that I know of, but we're always open to PRs if you want to add support for shaping a package out of the repo for distribution on UPM. I do have access to a public feed that I can distribute from once we have a package, but don't have bandwidth to do the packaging.

Are you suggesting that each nuget package could be delivered as a UPM package via a new registry (similar to how keijiro does it for his packages). If thats the case that could be awesome, though like you said, it does mean that the packages would have to hosted twice essentially and the bandwidth would have to be covered

**Comment by jwittner** [comment]
@andybak - we ignore the Assets/Packages folder and it's meta file in our .gitignore and it works great to keep third party stuff out of our repos. =)

**Comment by jwittner** [comment]
@popcron - this issue is about supporting the installation of NugetForUnity itself through UPM, not for supporting installation of Nuget packages through UPM. Right now the best way to get NugetForUnity initially installed is through the Releases here on GitHub. After that you can get updates through the Nuget menu in Unity, but it's just checking the Releases page and downloading the packages for you.

**Comment by assert-not-singularity** [comment]
I refactored the project so it is a valid UPM project. You can tryout by pressing the `+` button in the Unity Package Manager, clicking `Add package from git URL...` and entering `https://github.com/assert-not-singularity/NuGetForUnity.git#upm-package` or by adding the dependency `"com.glitchenzo.nugetforunity": "https://github.com/assert-not-singularity/NuGetForUnity.git#upm-package"` to the manifest.json.

There are still the CreateDLL and Packager folders in this branch it but they are not required anymore. Therefore, I did not try out if creating the `.unitypackage` still works. In my opinion, providing this package using UPM makes these redundant.

Please try out if downloading the package via UPM works for you as well. I would then open a PR, if desired. But be aware to not use this in any productive project since I will might delete this testing branch some day.

**Comment by popcron** [comment]
That's great! A self updater would be handy too.

**Comment by JoC0de** [comment]
Implemented in #480
