### ISSUE TITLE
Sanitize/Validate Source URLs

### ISSUE THREAD

**Issue by paco-ms** [GlitchEnzo/NuGetForUnity#249]
I mistakenly copy&pasted a source URL with an additional space at the end - this made requests fail. It wasn't difficult to figure out what happened, but it'd be great if those trailing spaces had been removed automatically, or a visible error message/dialog warned users when the URL didn't finish with a "/" character.

- **NuGetForUnity Version:** 1.1.0

**Comment by jwittner** [comment]
The URLs are simply concatenated right now. Would love to sanitize and convert to the UriBuilder for assembly. Marked this high pri due to the high natural propensity to run into these issues with the source URL input.

**Comment by thalbern** [comment]
I ran into this as well. What made it worse was that the package I was trying to install was already available at nuget.org but I wanted to install a newer version from a different source. So I ended up getting that old version (and testing that old version) because it wasn't apparent to me that I'm not accessing the right source.
