### ISSUE TITLE
Zip conflicts

### ISSUE THREAD

**Issue by bgulanowski** [GlitchEnzo/NuGetForUnity#261]
## Description

Installing NuGetForUnity creates conflicts with previously installed versions of DotNetZip.

Seems to only affect scripts compiled for the editor.

Workaround is to disable existing DotNetZip for editor. But this is not ideal: the version of DotNetZip won't be the same for scripts running in the editor versus built player.

Is there a way to disable the bundled DotNetZip that comes with NuGetForUnity? Delete it completely? I might try that.

What would happen if I tried to install DotNetZip through NuGetForUnity?

- **NuGet Package:** n/a
- **NuGetForUnity Version:** 0.0.13
- **Unity Version:** 2018.4.3.1f
- **Operating System:** macOS Mojave 10.14.5

**Comment by jwittner** [comment]
It's an interesting problem, and we're in a bit of a chicken and egg problem with DotNetZip. I believe we're using that over [ZipFile ](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile?view=netframework-4.5)because it works when targeting the Unity .Net 3.5 API.

@GlitchEnzo - any insight into how many N4U users are still targeting this?

**Comment by bgulanowski** [comment]
The other workaround also worked, I think, which was to disable the bundled version. But my whole motivation to use NuGetForUnity was to get a different NuGet package (SQLite-Extensions etc) working with IL2CPP. And that ultimately failed. So I reverted everything until I have more time to dig deeper.

**Comment by GlitchEnzo** [comment]
I'm sorry, but I no longer know the amount of users still targeting .NET 3.5, but I imagine it keeps steadily decreasing. I've long wanted to put in some simple analytics in to get better metrics for this, but I never got around to it.

At this point, it may be safe to upgrade to 4.0+ since the old version of N4U will still be around for the 3.5 users to use.

**Comment by dbacher** [comment]
Forget if Mono has a copy of System.IO.Packaging.
On .NET 3.5, System.IO.Packaging can be used to read zip files with no external dependencies - it's just a matter of if Mono supports it or not.

**Comment by jwittner** [comment]
Leaning toward dropping support for .NET 3.5 as it's deprecated by Unity now. Issue with moving to System.IO.Compression is that leveraging it means distributing a csc.rsp file in the root of the Assets folder. If consumers already had this file the import would overwrite it, and they'd have to use source control to understand what's going on. =(

**Comment by igor84** [comment]
Actually modifying csc.rsp is not needed. I have a fork where I removed DotNetZip in favor of System.IO.Compression and when I build NugetForUnity.dll and put it in Unity everything works without modifying the csc.rsp. I only need to modify it if I am putting actual NugetForUnity source files in Unity instead of dll.

**Comment by jwittner** [comment]
Very interesting @igor84 - I'll have to check that out!
