### ISSUE TITLE
Are we supposed to commit the dlls inside Assets/Packages?

### ISSUE THREAD

**Issue by kaynn** [GlitchEnzo/NuGetForUnity#319]
I dont see how it can work otherwise.

I have some code that requires some dll downloaded by NuGet (newtonsoft for example). But in order for Unity to initialize NugetForUnity.dll to download the dll, the whole project needs to compile. 

so a chicken-egg problem. Unless I'm missing something.

(I know this is not an issue, but I didnt know where to ask this)

thanks!

**Comment by jwittner** [comment]
Hi @kaynn - we commit the N4U dlls, but we don't commit Assets/Packages, in fact we explicitly ignore the folder in our .gitignore file. If you use the N4U dlls from the Releases here on Github rather than the source code, then Unity should initialize it and your packages will get restored. We rely on this behavior for the automated builds of our projects that use N4U, so I'm confident that it works.

Can you give some more context on the issue you're seeing?

**Comment by LiamKarlMitchell** [comment]
Is there a .gitignore or guide/best practices for developing unity projects with NuGetForUnity?
When team mates check out the repo and try to open it in Unity, its just full of errors.

**Comment by jwittner** [comment]
Hey @LiamKarlMitchell - we take the official Unity .gitignore and add the below lines at the end. The NugetForUnity contents should be included in the Source so that when teammates open up the project the Nuget dependencies are automatically resolved.

```
/Assets/Packages/
/Assets/Packages.meta
```

**Comment by LiamKarlMitchell** [comment]
Thanks very much @jwittner , that must be what I'm missing! :)

**Comment by jwittner** [comment]
If this works please close the issue. =)

**Comment by jwittner** [comment]
@Oneiros90 we've seen this too - Unity starts compiling, generates compiler errors, then it initializes the NugetForUnity dll and it restores the packages, causing Unity to recompile and eventually end up in a good state. Is that what you're seeing?

For our CI we actually run two invocations of our project. We run the project once from just get the packages restored. Then we run it again to invoke the actual build process.

**Comment by Oneiros90** [comment]
@jwittner no, what i'm seeing is just a first compilation and then errors coming from our code ("missing reference to nuget package") and that's it, NugetForUnity never gets initialized by itself (I can't see the Nuget menu in the menubar). The only way to fix it is to comment out the code that generates those errors, wait the compilation and only then NugetForUnity will start downloading the packages (and the commented code can be restored without errors)

**Comment by jwittner** [comment]
Are you using the NugetForUnity source code or the unity package from the [Releases ](https://github.com/GlitchEnzo/NuGetForUnity/releases/tag/v3.0.3)page? The unity package precompiles the assembly so Unity should be loading it regardless of other compilation errors. If you're using the source code I think you could add an assembly def to the folder and it'd achieve the same thing.

Curious about what versions of Unity/N4U/OS you're using and seeing this behavior if you are in fact using the precompiled assembly.

**Comment by Oneiros90** [comment]
Oh this can actually be an explanation. I'm using the source code because the packaged version was not cooperating in my case: I am interested in the [SocketIOClient](https://www.nuget.org/packages/SocketIOClient/) package but N4U failed to download its dependencies properly. I had to manually change some lines of code to avoid it skipping some dependencies that it thought was already included in the engine.
Is there a reason why the asmdef is not already provided in the source code? It makes sense, it could be our solution

**Comment by Oneiros90** [comment]
> Regarding the above, I'd love to have an issue filed for any dependencies that we're deducing are included in Unity that you're finding aren't. Any chance you can do that?

I just did it [here](https://github.com/GlitchEnzo/NuGetForUnity/issues/426), thank you @jwittner :)

**Comment by lgarczyn** [comment]
For other users, if you're using the /Packages folder instead of /Assets/Packages use this

```gitignore
/Packages/nuget-packages/InstalledPackages
/Packages/nuget-packages/InstalledPackages.meta
```
