### ISSUE TITLE
Confluent.Kafka package missing libraries.

### ISSUE THREAD

**Issue by 0x6c6565** [GlitchEnzo/NuGetForUnity#325]
## Description
The libraries aren't downloading and I'm getting an error that the __librdkafka.dll__ failed to load when I try to build a kafka producer.

I've tried both with and without _Allow Unsafe Code_.

- **NuGet Package:** Confluent.Kafka.1.3.0
- **NuGetForUnity Version:** Most recent download
- **Unity Version:** Unity 2019.3.3
- **Operating System:** Windows 10

**Comment by JoC0de** [comment]
At the time this issue was created this package wasn't actively maintained. So sorry for eventual trouble. Now there are some new active contributors. 

Confluent.Kafka depends on librdkafka.redist that requires some native dll to be published with the application currently this is not handled by NuGetForUnity automatically. PR #419 will fix this.
![image](https://github.com/GlitchEnzo/NuGetForUnity/assets/53140583/5bcf44b8-49c3-4fce-9cef-c38bed23bf04)

**Comment by JoC0de** [comment]
Fixed by #631
