### ISSUE TITLE
Some packages are also installing CSharp (causing conflicts in unity)

### ISSUE THREAD

**Issue by iwillreku3206** [GlitchEnzo/NuGetForUnity#328]
## Description
Hypixel.Net requires Microsoft.CSharp 4.7.0 which causes NugetForUnity to install C# as a Nuget package

- **NuGet Package:** Hypixel.Net
- **NuGetForUnity Version:** 2.0.0
- **Unity Version:** 2019.3.10f1
- **Operating System:** macOS 10.15

**Comment by iwillreku3206** [comment]
I figured out that changing the Api compatibility to .NET 4.x instead of .NET standard 2.0 solved the issue for me

**Comment by neilyio** [comment]
I also had this problem and it cost me most of the day. I'm pretty new .NET and Unity so it was tough to debug, but it was also very difficult to Google the problem. I was trying to install [language-ext](https://github.com/louthy/language-ext) and got dozens of CS0433 errors because of the conflicts

Could anyone here elaborate on why this happens? Could the documentation be updated to address this?

**Comment by jwittner** [comment]
Installing Microsoft.CSharp usually works ok in Unity - we have several use cases. There tend to be more problem when targetting .Net Standard packages as they rely on lots of packages that are included by default in the .Net Framework and in Unity, but NugetForUnity doesn't currently have a mapping of what libraries Unity has included out of the box so you can get conflicts.

We've discussed scanning the install directory of the current version of Unity and deleting libraries that came from NuGet packages if Unity already has a matching assembly, but it's not functionality currently in N4U.

Hope that clarifies some!
