### ISSUE TITLE
When I import this package,  Under the Assets folder the Packages folder all contents has been deleted, That's real unfriendly design！

### ISSUE THREAD

**Issue by a358003542** [GlitchEnzo/NuGetForUnity#402]
When I import this package,  Under the Assets folder the Packages folder all contents has been deleted, That's real unfriendly design！

**Comment by cyraid** [comment]
It was designed to be imported in Assets Folder, why would you go below that?

**Comment by a358003542** [comment]
@cyraid Just a warning, For Some personal reason, maybe some people put his packages all organized in the `/asssets/packages` folder, In some case.

**Comment by cyraid** [comment]
But since it's a .unitypackage, those are to be imported in the assets folder. It even has the special folder 'editor' to put up a menu item. The case of there being an existing /assets/packages there maybe could be a warning saying the folder exists and maybe rename it to packages.bak or give a warning? I do understand why the folder would need to be wiped.

**Comment by a358003542** [comment]
@cyraid Still i think the `/assets/packages` folder as nuget package station name is too general, maybe there is a warning message, but maybe some user ignore it because they do not understand what's that mean or click too quick not pass this import message.
