### ISSUE TITLE
Error while running OnnxRuntime

### ISSUE THREAD

**Issue by pytholic** [GlitchEnzo/NuGetForUnity#420]
Hi. Thank you for the package.

I am working with OnnxRuntime side Unity3D. I installed Microsoft.ML.Onnxruntime packages using NugetForUnity. However, at runtime I run into this exception:

`EntryPointNotFoundException: OrtGetApiBase
Microsoft.ML.OnnxRuntime.NativeMethods..cctor () (at <2b5de034e06549d8a90fddfdbe8a7978>:0)
Rethrow as TypeInitializationException: The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.
Microsoft.ML.OnnxRuntime.SessionOptions..ctor () (at <2b5de034e06549d8a90fddfdbe8a7978>:0)
Microsoft.ML.OnnxRuntime.InferenceSession..ctor (System.String modelPath) (at <2b5de034e06549d8a90fddfdbe8a7978>:0)
TestScript.Start () (at Assets/Scenes/TestScript.cs:74)`

The same script and setup works fine with my previous approaches in which I manually made Onnxruntime setup using .dll files and it worked fine with Unity scripts. Now I wanted to try NugetForUnity package manager for installation but I ran into this. Any guidance?

**Comment by JoC0de** [comment]
OnnxRuntime is a native package (it requires native e.g. C++ Dll's) witch is currently not supportet by NuGetForUnity. See fPR #421

**Comment by asus4** [comment]
Hi, thanks for supporting native runtimes! I installed the `Microsoft.ML.Onnxruntime` package via NuGetForUnity and worked perfectly on macOS Editor and Android. However, the link on iOS fails because the `*.xcframework.zip` is not supported.

- Tested on 
  - Unity: `6000.3.11f1a`
  - NuGetForUnity: master branch acc1c7b

 Xamarin added support for `*.xcframework.zip` in the `<NativeReference>` at https://github.com/dotnet/macios/pull/21492 . It would be great if this library also supported it.
