### ISSUE TITLE
Multiple precompiled assemblies Error

### ISSUE THREAD

**Issue by DomenPigeon** [GlitchEnzo/NuGetForUnity#453]
I get this errro when installing the SignalR client package.
```
Multiple precompiled assemblies with the same name System.Text.Json.SourceGeneration.resources.dll included or 
the current platform. Only one assembly with the same name is allowed per platform. 
(Assets/Packages/System.Text.Json.6.0.4/analyzers/dotnet/roslyn4.0/cs/zh-Hans/System.Text.Json.SourceGeneration.resources.dll)
```

**Comment by unikzforce** [comment]
I had this error couple of years ago, It still has not been solved, I guess never will. no one had the ability to change this

**Comment by jwittner** [comment]
> I had this error couple of years ago, It still has not been solved, I guess never will. no one had the ability to change this

We've had similar errors over the years.

**Comment by DomenPigeon** [comment]
Probably this kind of errors won't be solved until Unity creates an internal solution for nuget packages ...

**Comment by NoTuxNoBux** [comment]
I think this happens because some packages include analyzers with the same name for what appears to be multiple locales:

![afbeelding](https://user-images.githubusercontent.com/73220431/186871587-62bb2524-cbe8-496b-a16c-b0779f540c4d.png)

Part of the problem might be that NuGetForUnity does not recognize analyzer DLLs as such (https://github.com/GlitchEnzo/NuGetForUnity/pull/393 adds that), but even then it's likely still problematic because it doesn't know which localized resource file to select. [There is some information here](https://github.com/dotnet/roslyn/blob/main/docs/analyzers/Localizing%20Analyzers.md) on how localization works for analyzers. From what I understand, the English variant (default) is inside the main assembly, meaning it _should_ be possible for NuGetForUnity to just drop said localized variants during installation for the time being.

**Comment by JoC0de** [comment]
My workaround https://github.com/GlitchEnzo/NuGetForUnity/issues/472#issuecomment-1359214598
