### ISSUE TITLE
Always got a "Multiple precompiled assemblies" error

### ISSUE THREAD

**Issue by 2catycm** [GlitchEnzo/NuGetForUnity#472]
## Description
[Describe the issue you have.]

- **NuGet Package:** [What is the name and version of the NuGet package you are installing?]

I am trying `Netonsoft.Json` ,  `System.Text.Json` and `Lombok.NET`

None of them actually works. 
Step to reproduce:
1. Install NuGetForUnity by importing the package. 
2. Open by clicking NuGet Menu. 
![image](https://user-images.githubusercontent.com/41530341/206857674-7553a09b-d385-4dfd-922b-7e2bd013cfce.png)
3. Install seems successfully, but never passes the compilation. 
For example:
- Lombok.dll
Multiple precompiled assemblies with the same name Lombok.NET.dll included on the current platform. Only one assembly with the same name is allowed per platform. (Assets/Packages/Lombok.NET.2.0.0/lib/netstandard2.0/Lombok.NET.dll)

Multiple precompiled assemblies with the same name Lombok.NET.dll included on the current platform. Only one assembly with the same name is allowed per platform. (Assets/Packages/Lombok.NET.2.0.0/analyzers/dotnet/cs/Lombok.NET.dll)

These files both exists. And unity doesn't know which to import. 

I tried to manually delete one of these files, but new error occurs.
![image](https://user-images.githubusercontent.com/41530341/206857791-5c4e0a09-5c75-4f05-af38-6d40b72e4139.png)

- Newtonsoft.json
![image](https://user-images.githubusercontent.com/41530341/206857829-70f2b46f-af1d-42b5-b1f1-19f2d8afd642.png)

This is because with the unity comes the default old com.Unity.Newtonsoft.Json. And I cannot remove it.  

![image](https://user-images.githubusercontent.com/41530341/206857890-5af2db44-3215-4854-9043-ac2b6ffd1c74.png)

- System.Text.Json

![image](https://user-images.githubusercontent.com/41530341/206857951-e2cd9c19-5808-4ba5-8647-99e8e5fbe478.png)

I am new to Unity and C#, but I am shocked that simply importing a library can be so complex in Unity game development. I think your work trying introducing NuGet into Unity is really awesome.  Can you help me solve the above problem? Maybe the package I have choosen happens to be something with "Microsoft" or "System" that makes things complex because it may conflict with the dotnet sdk or unity sdk? 

- **NuGetForUnity Version:** [What version of NuGetForUnity are you running?]
Version 3.0.5

- **Unity Version:** [What version of Unity are you using?]

2021.3.14

- **Operating System:** [What OS are you on?]
Windows 11

**Comment by JoC0de** [comment]
I had the same issue, the problem is that System.Text.Json has multiple resource.dll files (one for every language), Unity / NuGetForUnity doesn't understand the folder hierarchy and just includes all of them witch leads to the error you are getting. There is a Workaround: disable the loading of the resources.dll files by disabling them for all platforms. This can be done with simple text "search and replace", I used grepWin but Visual Studio etc. also supports it, select the folder and replace `enabled: 1` with `enabled: 0` inside all the `*.dll.meta` files located under `System.Text.Json.7.0.0\analyzers`.
<img width="402" alt="image" src="https://user-images.githubusercontent.com/53140583/208655738-7bd207b6-ec08-4d27-bbdc-64bfa7b39cc0.png">
Eventually you need to re-enable one of the languages but for me it is working as the analyzers are only a Build-Time thing so they are optional.
