### ISSUE TITLE
Missing Packages after migrating repo

### ISSUE THREAD

**Issue by AvaThalheim** [GlitchEnzo/NuGetForUnity#526]
## Description

We recently migrated our unity project into a new git repo, and it seems all references to installed NuGet packages got lost on the way. 
I haven't found a similar issue and was wondering if there is a specific thing that needs to be done in order for that to work. 

The NuGet config file is located inside the Assets folder. 
We have those 3 packages installed: 

Microsoft.MixedReality.OR - Version 0.5.3037
Microsoft.MixedReality.Unity,FrozenWorld,Engine - Version 1.1.1
Microsoft.VCRTForwarders.140 - Version 1.0.7

The packages are all present in the original project.
On the server however, they appear missing. 

![image](https://github.com/GlitchEnzo/NuGetForUnity/assets/25528287/bc5b60ce-405b-4db1-8e9e-2780e3b9517e)

Any help would be greatly appreciated! 

-   **NuGetForUnity Version:** [3.0.2]
-   **Unity Version:** [2019.4.4fi]
-   **Operating System:** [Win10]

**Comment by JoC0de** [comment]
Hi @AvaThalheim thanks for reporting the issue.
Sorry for the delay, I was bussy. I don't relay understand what's your problem if you move the `Assets/NuGet.config`  to the new repo everything should be fine. NuGetForUnity just reads / writes to the file. Eventually it was recreated (empty) because you opened unity without the file. It should look something like [src/TestProjects/ImportAndUseNuGetPackages/Assets/NuGet.config](https://github.com/GlitchEnzo/NuGetForUnity/blob/master/src/TestProjects/ImportAndUseNuGetPackages/Assets/NuGet.config). Are you able to reinstall the packages using the "NuGet" window?

**Comment by AvaThalheim** [comment]
Hi @JoC0de,

The issue is, that we made an exact copy of a project, including the NuGet.config file, and uploaded it into a new repo. 
The new repo however does NOT have the packages. 
Since the buildserver is generating the project on the go, based on the version in the repo, the packages are never included. 


![image](https://github.com/GlitchEnzo/NuGetForUnity/assets/25528287/e6f1a8f0-20f9-4046-be4b-01f15a128596)

**Comment by AvaThalheim** [comment]
![image](https://github.com/GlitchEnzo/NuGetForUnity/assets/25528287/3ff77125-3de0-4061-9855-56f35cc85414)

**Comment by JoC0de** [comment]
Oh sorry I scrambled it up. I meant the package.config file
like https://github.com/GlitchEnzo/NuGetForUnity/blob/master/src/TestProjects/ImportAndUseNuGetPackages/Assets/packages.config

**Comment by igor84** [comment]
You can try to enable Verbose logging in NugetForUnity preferences and then try to see in the logs what happens when you try to restore packages or when you load the project.

**Comment by AvaThalheim** [comment]
I enabled verbose logging and got the following error messages: 

![image](https://github.com/GlitchEnzo/NuGetForUnity/assets/25528287/48171cfd-83b3-4d0c-9410-b66436d03173)
