### ISSUE TITLE
Nuget 3.0.2 on Unity 2020.3.40 Check for Updates error

### ISSUE THREAD

**Issue by RubenGarcia** [GlitchEnzo/NuGetForUnity#550]
## Description

Clicking on Check for Updates gives me a window
```
Couldn't find release information at
https://github.com/GlitchEnzo/NuGetForUnity/releases
```

-   **NuGet Package:** N/A
-   **NuGetForUnity Version:** 3.0.2
-   **Unity Version:** 2020.3.40
-   **Operating System:** Windows

**Comment by JoC0de** [comment]
Thanks for creating the issue,
In version 3.0.2 the "Check for Updates" functionality was brocken.
Just update manually by installing it according to the documentation https://github.com/GlitchEnzo/NuGetForUnity/tree/master#how-do-i-install-nugetforunity
I would recommend the `Install via OpenUPM` or `Install via Package Manager` installation method because it can be shared with team members without all needing to install them manually.
