### ISSUE TITLE
Store only nuspec instead of whole nupkg in package install folder

### ISSUE THREAD

**Issue by igor84** [GlitchEnzo/NuGetForUnity#556]
Currently when a package is installed its nupkg file is downloaded to nuget cache folder and also copied to the folder in the project where it is decompressed. This file is then used in `NugetHelper.UpdateInstalledPackages()` method where we call `NugetPackage.FromNupkgFile` to get info on the installed package but this method also checks if nuspec file exists instead to read info about installed package from it. On the other hand `CheckForUnnecessaryPackages()` method is skipping all folders that don't contain nupkg files and I as far as I see it should also not skip folders that contain nuspec files.

Anyway this means that whenever UpdateInstalledPackages is called it has to decompress the nuspec file from nupkg of each installed package and there is no other reason for nupkg to exist. That is why I propose we store just the nuspec file and not the whole nupkg in installed package folder making reading nuspecs much faster.

**Comment by popara96** [comment]
Note: two tests seem to be failing with the error `InvalidDataException: End of Central Directory record could not be found.`. They are both related to `protobuf-net.2.0.0.668` package, and I am probably missing something here and am not sure why it is unable to unzip this package now, since it's downloaded to cache the same way as before. Newer versions of this package don't have this issue when manually installing (I tried with `3.2.26`).
