### ISSUE TITLE
Consider using Nuget.Protocol nuget package for feed communication

### ISSUE THREAD

**Issue by igor84** [GlitchEnzo/NuGetForUnity#559]
I just discovered there is a library for communicating with [Nuget feeds](https://www.nuget.org/packages/NuGet.Protocol#readme-body-tab). Maybe we should consider using it instead of maintaining our own implementation.

**Comment by JoC0de** [comment]
While implementing the API V3 I also thought about using the NuGet packages as ist would have made everything easier / more standard conform. But I couldn't find a way that satisfies "my" understanding of open-source software / dependency management. For NuGetForUnity to use any NuGet package we would need something like NuGetForUnity 😄 
Options:
1. Add the `.dll` of the NuGet package to our GIT. I don't like having raw '.dll'`s inside git it probably even violates the License of the used Library.
2. Download the `.dll` on the fly when running NuGetForUnity the first time. But how to download? Without a nuget client? What if the user has no internet access? ...

**Comment by JoC0de** [comment]
It is not "one single" `.dll` we would need to copy into our GIT and distribute to everyone. We need all dependencies of the package. And we need to ensure that they all work with all Unity versions we support. E.g. the NuGet package uses Newtonsoft.Json for JSON parsing instead of Unity's own / adapted Json libraries. If a user tries to install a package that we already included as a `.dll` we would need to handle it specially so that the user only installs a package as a Runtime dependency but I think we have a problem when a User tries to install a different version from the one included in NuGetForUnity.
In the closed PR about API V3 there was a try to implement it using the NuGet package: https://github.com/GlitchEnzo/NuGetForUnity/pull/406/files#diff-b2f8ab158a9c572cfb857f1714269762184b6b3fd8766d77c252df246ed9d63b 
![image](https://github.com/GlitchEnzo/NuGetForUnity/assets/53140583/5b75f476-edd1-4f5e-9ec3-bab081d66529)
I see many possible issues and no real advantage. Another problem could be that we lose control over many parts of the code that we than cannot change as they are inside a dependency. Including the whole source code would make Unity much slower as it need to compile the code (at least when switching platforms, opening the project for the first time).

**Comment by igor84** [comment]
You are right. Thanks for explaining it. I will close this.
