### ISSUE TITLE
Optimize GetAlreadyImportedLibs method

### ISSUE THREAD

**Issue by igor84** [GlitchEnzo/NuGetForUnity#561]
GetAlreadyImportedLibs method takes the most time and allocates the most memory after each recompile of the project. We should see if we can optimize it somehow. The most obvious thing is not to call `CompilationPipeline.GetAssemblies` twice, but call it once and use the same result for both operations.

**Comment by JoC0de** [comment]
`CompilationPipeline.GetAssemblies` is actually called with different parameters:

1. getting all Player assemblies:
https://github.com/GlitchEnzo/NuGetForUnity/blob/25d19abe5a3942980a3476feafe0ba42a1bbd854/src/NuGetForUnity/Editor/UnityPreImportedLibraryResolver.cs#L43-L45

1. getting all Editor assemblies:
https://github.com/GlitchEnzo/NuGetForUnity/blob/25d19abe5a3942980a3476feafe0ba42a1bbd854/src/NuGetForUnity/Editor/UnityPreImportedLibraryResolver.cs#L64

I only see a improvement in caching the result either inside a file or a ScriptableObject so they can persist if unity reloads.
But we need to ensure that the list is reloaded if one of the following changes:
- ApiCompatibilityLevel
- Unity version
- Packages installed by Unity Package Manager
- Build target platform

But it should be possible.

**Comment by igor84** [comment]
Ah, you are right. The documentation does say AssemblyType is Flags kind od enum though, so it might have been worth the try to combine them but actually much, much better improvement would actually be to skip dependency resolution completely when doing a Restore.

**Comment by popara96** [comment]
@JoC0de I'm planning to do a PR where I would skip `GetAlreadyImportedLibs` when we're doing `Install`/`Update` through `Restore`, and I would also skip installing dependencies in that case since installing/updating packages should already properly list the packages and their respective versions in `packages.config` which `Restore` reads. This would also mean that I would be sacking the `Lock Packages on Restore` feature in preferences, as it would be redundant because this would be a default and only behaviour. What do you think about this?

**Comment by JoC0de** [comment]
Some Thought / what I would do:
- Store a `package-lock.json` somewhere, outside the Unity project e.g. in the `Library` folder as it is like a cache (for what has been installed). It shouldn't be inside git so I would put it outside the Asset folder.
- Store Current ApiCompatibilityLevel inside the `package-lock.json` so changing the setting will produce a "full Restore"
- perform "full Restore" if a user klicks on the MenuItem and do a "quick restore on all the automatic cases. So user can fix issues by Performing it manually. Because e.g. adding a `csc.rsp` or installing a UPM package can theoretically change the `AlreadyImportedLibs` and therefore exclude some packages from being needed.
- Store current Unity version inside the `package-lock.json` so updating will also trigger a "full Restore"
- On a "slim Restore" we only check if every package that is listed inside `package.config` is also inside the `RepositoryPath` (its `.nuspec` file)

`package-lock.json` is just a "WIP name" depending on what information it will contain it could be also sort of a `nuget-for-unity-restore-medatata.json`

`Lock Packages on Restore` would be a setting that always performs a "slim Restore" so we can keep it but I don't know if it has a use case, probably if you like to force "slim Restore" on a fresh checkout.

**Comment by igor84** [comment]
We actually really want "slim Restore" on a fresh checkout that will happen on our build machines, because we want our builds to be reproducible and with no surprises. In other words we want to setup our project locally in one way and have it build on build machines in that way and report errors if it can't so that we can detect if we have some wrong build settings.

The way we work I would like that option for all automatic Restores to be slim and only the menu item to be full. That would mean that I can again set up my project locally when I update Unity or change api compatibility, but I do it manually and thus consciously and with understanding on what changes I am making to my project. Having that be done automatically is nice but I am not so sure it is a better option really...

What do you think about that?

**Comment by JoC0de** [comment]
The problem is Unity allows setting `ApiCompatibilityLevel` based on build target, so you can have Windows build with `.Net Framework` and iOS build with `.Net Standard` both created from the same project. Also it is possible to configure Assembly Definitions that import system libraries using `csc.rsp` to be only imported on specific platforms [Creating a platform-specific assembly](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html).
So I thought a user that switches the Platform inside the Editor, or even on a build pipeline building for multiple build targets one by one, should not be required to do a manual "full Restore".
On all build pipelines that I have setup I used the CLI version, that does a slim restore, by definition.
But I also see that e.g. "setting `ApiCompatibilityLevel` based on build target" is a think that probably not many people require. I am not sure if there are still platforms that only support a certain `ApiCompatibilityLevel` setting like Linux probably don't support `.Net Framework`. Eventually we can add a different setting to mitigate this e.g. making the whole "soft Restore" opt-out for advanced use cases.

**Comment by igor84** [comment]
I was hoping we can make this with simpler implementation and only make it complicated if users really need it but I guess the risk of breaking people's workflow is too great. Open source is hard 😀.

**Comment by JoC0de** [comment]
I think the easiest would be to make the whole "slim Restore" opt-out so we only need to implement the additional case and keep the existing at least it wouldn't require us to create a file that keeps track about the last used `ApiCompatibilityLevel`. But we at least need some good documentation for it or analyze the `ApiCompatibilityLevel` per-platform setting to automatically disable the feature if the project has a complex setup (make it opt-in instead of opt-out).
