### ISSUE TITLE
Allow for auto-updating of NuGet

### ISSUE THREAD

**Issue by GlitchEnzo** [GlitchEnzo/NuGetForUnity#62]
It should detect if a new version of NuGet For Unity is available and prompt the user to install it.

**Comment by GlitchEnzo** [comment]
Perhaps this should be a separate .nupkg that is an "extension" to NuGet that looks for a .unitypackage on a server somewhere.

**Comment by ForrestTrepte** [comment]
This is cumbersome when we have a new version and need to copy updated version of the dlls into all our projects. I like the idea of making NuGetForUnity a package so that it can update itself via its own interface. But then how would a user get an initial version of NuGetForUnity. Our projects are checked in with the Packages folder ignored, so if NuGetForUnity were a package then an initial clone of the project wouldn't contain a version of NuGetForUnity that could be used to bootstrap it.

**Comment by jwittner** [comment]
Now that this is in the asset store, is that the best way to update?

**Comment by jwittner** [comment]
For reference the nuget cli updates itself via `nuget update -self`

**Comment by ForrestTrepte** [comment]
@jwittner and I thought of a low-tech solution. Add a "Check for Updates" menu item that launches the https://github.com/GlitchEnzo/NuGetForUnity/releases page. Then users can click on the .unitypackage to install it with Unity.

@GlitchEnzo, how does that sound to you? Also, do you mind if we make new releases of NuGetForUnity when there are new features we want to pull into our projects?

**Comment by GlitchEnzo** [comment]
My original idea was to have a separate NuGet package that contained the "NuGet For Unity Updater". This would query a server for a simple XML file that listed the version and the URL to the .unitypackage file to download & install.

My initial work was done here: https://github.com/GlitchEnzo/NuGetForUnityUpdater

I'm okay with the "Check for Updates" approach that points to the GitHub releases.

**Comment by ForrestTrepte** [comment]
Thanks for the flexibility, @GlitchEnzo. The Check for Updates approach seemed simple to implement and I liked the idea that is uses the release approach that you already have in place. Let's try it and we could always move to something more sophisticated such as an updated package at a later date.

**Comment by jwittner** [comment]
Simple workflow is now available!
