### ISSUE TITLE
.Net 4.x Could not resolve type with token

### ISSUE THREAD

**Issue by Merglasch** [GlitchEnzo/NuGetForUnity#77]
When using the Package manager with the current beta version of unity (which supports .net 4.x) opening the manager throws a System.TypeLoadException: Could not resolve type with token 01000037 originating at NugetForUnity.NugetPackageSource.Search

**Comment by GlitchEnzo** [comment]
I haven't used the latest beta of Unity, but it makes sense that you'd be having issues with .NET 4.x libraries. Since all prior versions of Unity only supported .NET 3.5, I have it automatically strip off any libraries that target a higher version of .NET.   I'll have to add a check for the Unity version and then allow .NET 4.x libraries.

**Comment by GlitchEnzo** [comment]
#76
