### ISSUE TITLE
automatic restore operations slow down development

### ISSUE THREAD

**Issue by ForrestTrepte** [GlitchEnzo/NuGetForUnity#94]
Each time you hit Play, a NuGet restore operation is run. This can take a while, particularly on a machine running over WiFi. There may be other cases in addition to hitting play when restore is run.

In order to speed up development, I'm thinking of adding an option to preferences that disables automatically running the restore operation. A Restore button or menu item would be added that would explicitly trigger a restore.

Users could disable automatically running restores, resulting in faster development at the cost of possibly becoming out of date if you forget to manually run a restore.

**Comment by jwittner** [comment]
I believe there is already a restore option in the menu to invoke the operation - we just need a way to disable the default behavior of restoring after code compiles.

**Comment by GlitchEnzo** [comment]
The restore operation when entering play mode _was_ disabled with [this commit](https://github.com/GlitchEnzo/NuGetForUnity/commit/d77ac36d5a8a579b1212fca3cd3e26e5d2e34df7) last year.  Perhaps the newer versions of Unity have changed that behavior?  I can investigate.

I don't believe we want to eliminate the auto-restore feature.  It was done as a convenience so that when a user pulls down a fresh Unity project from source control, the packages are automatically restored with no manual step.  Several people specifically requested this feature and like having it.

**Comment by ForrestTrepte** [comment]
I did a little experimentation and found:
1. The delay I was seeing on Play is not actually a restore. It occurs in NugetWindow.OnEnable. When you play, Unity calls this if the NuGet window is present. (Play is pretty fast if you close your NuGet window.)
2. When editing scripts, I am seeing a delay due to Restore. This adds about a 9 second delay to Unity's update whenever I make a code change.

For 1, I am thinking of trying an EditorApplication.isPlayingOrWillChangePlaymode early-out for NugetWindow.OnEnable similar to what is currently in the static NuGetHelper constructor.

For 2, I'm thinking of looking for a way to detect that a compile has occurred. Unfortunately, EditorApplication.isCompiling is false when the static NuGetHelper constructor is called. So I may need for an alternative approach or--as @GlitchEnzo describes--create a preference to disable automatic restores.

**Comment by ForrestTrepte** [comment]
I have a pull request for the first issue above and [asked a question](http://answers.unity3d.com/questions/1418351/how-to-run-a-script-once-when-a-project-is-first-l.html) about the second issue on Unity Answers.
